### PR TITLE
Use strip-bom to get rid of a UTF Byte Order Mark

### PR DESCRIPTION
**Pull request by rohbotics**
Issue #130

### CODE REVIEW

**Comment by robconery** [comment]
Lovely - thank you! Just want to be sure all tests are passing? I haven't hooked up Travis yet... which I keep meaning too...

**Comment by rohbotics** [comment]
How do I run the tests?

**Comment by robconery** [comment]
Make sure you have mocha installed: `npm install mocha -g` and then have Postgres installed locally. Create a login that matches our test login (or change it to suit) and then run `mocha .` - don't forget the dot :).

**Comment by rohbotics** [comment]
All looks good,
213 passing (11s).

**Pull request merged**
