### PR TITLE
Fix logo

### PR DESCRIPTION
**Pull request by robinjmurphy**
It went missing :cry:

### CODE REVIEW

**Comment by xivSolutions** [comment]
@robinjmurphy - Any idea why the Travis CI build is failing on this branch?

**Comment by robinjmurphy** [comment]
It'll be because the 9.5 tests aren't skipped in this branch.

**Comment by xivSolutions** [comment]
Ahh...got it.

**Comment by xivSolutions** [comment]
@robinjmurphy FYI - Rob added you to commit, so when you feel comfortable, you can do your own merges and such. Personally, I have no qualms just merging stuff like test fixes, and the logo fix. When it comes to architectural decisions or significant new features, I tend to wait for Rob to at least weigh in. 

Nice work - really appreciate your additions. Are you using this in prod somewhere?

**Comment by robinjmurphy** [comment]
Thanks @xivSolutions. Will do that from now on. Yep, we're using it at the BBC to power bits of [iPlayer](http://www.bbc.co.uk/iplayer).

**Pull request merged**
