### PR TITLE
Massive had no support for composite pk or tables with no pk

### PR DESCRIPTION
**Pull request by kzar79**
Tables without pk were simply ignored.

Tables with composite pk behaved strangely.

### CODE REVIEW

**Comment by robconery** [comment]
There are a number of things that won't work without the way we handle primary keys; it's not something I'm wanting to support with Massive. In addition, there are no tests in any of the commits you've offered here.

Code aside, as a database aficionado I can see 0 reasons why a composite key is preferable outside of a many to many, and I see absolute NO case where omitting a PK is acceptable.

**Comment by dmfay** [comment]
Junction tables sometimes outgrow their original remits -- I've got one that's tracking a status field in addition to the relationship, for example. Fortunately I only need to insert via Massive so the composite key issue doesn't come up, but similar situations might not work out so cleanly.

**Comment by kzar79** [comment]
1. I have two tables without a pk, because they are just a collection of attributes linked to another table. So I just have an "on update delete" on their fk, and when I select them I do it through the fk and always need all of them. If I really wanted a pk on that table, that would be a composite key, anyway.

2. Composite keys are quite common in real-life databases.

Anyway, if you don't think that could be useful, no need to include them in the master. I will keep using my fork with my changes, I solved my problem and I'm happy with that.

**Comment by xivSolutions** [comment]
@kzar79 - Cool that you solved the problem. This issue pops up from time to time. As I'm sure you know, designing any software involves a series of trade-offs. In our case we decided to prioritize simplicity over adding a ton of features that serve primarily edge-cases (the 80/20 rule, sort of). 

We recognize that Db's exist in the wild with composite keys, and with tables with no defined key. While composite keys are not necessarily a true "edge case" (particularly when it comes to reference tables and the like), we felt they do fall into that 20% area. 

Tables with no key are, to us, a true edge case, and often a Db design "smell" (though not always! I get it, and have done so myself :-)). 

One potential work-around may be to use a SQL file for either of those cases. Massive is actually predicated on the notion that the lib should really only do so much - or, as a wise man once put it, "SQL is the best DSL for talking to a database." Bolting SQL files on as functions is an encouraged design choice within Massive. 

Massive attempts to put an abstraction layer of the most common, repetitive stuff you might otherwise find yourself coding ad nauseum. It does not purport to be a full-fledged ORM (in fact, it goes out of its way NOT to be). 

Glad you were able to implement a solution that works for your project, and glad you are finding the lib useful :-)

**Pull request closed without merging**
