### PR TITLE
Bubble instead of throwing on connection errors so application can im…

### PR DESCRIPTION
**Pull request by AlexZeitler**
Bubble instead of throwing on connection errors so application can implement retry pattern.

### CODE REVIEW

**Comment by AlexZeitler** [comment]
@robconery @xivSolutions @dmfay Beside the conflicts that must be resolved because the code in the PR is now outdated anything thats blocking this PR?

**Comment by robconery** [comment]
I need to think about it a bit more. Not being able to connect should throw... and I just want a little time to think this through as it doesn't directly address the problem, it's essentially a hack to allow your situation to work (and I'm sure others might have this situation as well).

I want to address this, but I'm wavering a bit on whether bubbling a connection error is the right way.

**Comment by dmfay** [comment]
For whatever it's worth I am pro-bubbling in general and would prefer to be able to decide what to do with a connection error without any extra try/catch rigmarole on top of the existing error checks in my callbacks.

**Comment by jadams74** [comment]
What happened w/ this pr? It is not clear to me. We have the same use case.

**Comment by robconery** [comment]
We merged #257, you can click it right there above your comment. We're now passing defaults and bubbling errors...

**Pull request closed without merging**
